#! IMPORTANT NOTE: This file is used for default configuration variables. Can be overridden by using environment variables(Example: Heroku config vars).
configName: conformance

server:
  port: 8080

authorization:
  # "issuer": "https://api-conformance.ebsi.eu/conformance/v3/auth-mock" GENERIC
  issuer: ""
  authorization_endpoint: /auth/authorize
  token_endpoint: /auth/token
  # custom
  direct_post_endpoint: /auth/direct_post
  # end custom
  jwks_uri: /auth/jwks
  scopes_supported:
    - openid
  response_types_supported:
    - vp_token
    - id_token
  response_modes_supported:
    - query
  grant_types_supported:
    - authorization_code
  subject_types_supported:
    - public
  id_token_signing_alg_values_supported:
    - ES256
  request_object_signing_alg_values_supported:
    - ES256
  request_parameter_supported: true
  request_uri_parameter_supported: true
  token_endpoint_auth_methods_supported:
    - private_key_jwt
  vp_formats_supported:
    jwt_vp:
      alg_values_supported:
        - ES256
    jwt_vc:
      alg_values_supported:
        - ES256
  subject_syntax_types_supported:
    - did:key
    - did:ebsi
  subject_trust_frameworks_supported:
    - ebsi
  id_token_types_supported:
    - subject_signed_id_token
    - attester_signed_id_token

credential:
  vc_data_endpoint: /credentials/external-data
  deferred_vc_register: /deferred/register/
  deferred_vc_exchange: /deferred/exchange

verifier:
  vc_data_endpoint: /presentations/external-data

authentication:
  session:
    secret: SeCr€t $-load
    expiration: 3600

logs:
  console:
    active: true
    level: debug
  file:
    active: true
    level: debug
    path: "/files/logs/logs.log"
  graylog:
    active: false

language:
  allowed:
    - es
    - en
  default: en
  location: "/shared/files/locales"

ebsi:
  didr_url: https://api-conformance.ebsi.eu/did-registry/v5/identifiers
  tir_url: https://api-conformance.ebsi.eu/trusted-issuers-registry/v5
  verify_term_of_use: false
  status_list_schema: https://api-conformance.ebsi.eu/trusted-schemas-registry/v3/schemas/z6WWNVGZkYCMyT5YifMSbBxJ5qrRY6GT3PqNBh6SbMQpW
  did_registry_rpc_endpoint: https://api-conformance.ebsi.eu/did-registry/v5/jsonrpc
  ti_registry_rpc_endpoint: https://api-conformance.ebsi.eu/trusted-issuers-registry/v5/jsonrpc
  besu_rpc_endpoint: https://api-conformance.ebsi.eu/ledger/v4/blockchains/besu
  auth_ebsi_server_url: https://api-conformance.ebsi.eu/authorisation/v4