#! IMPORTANT NOTE: This file is used for default configuration variables. Can be overridden by using environment variables
configName: local

server:
  port: 8080
  scope_action_endpoint: "http://identfy-entity-backend-backend-1:8000/vc-scope-action"

nonce_service:
  url: "http://identfy-entity-backend-backend-1:8000/nonce-manager"

authorization:
  # "issuer": "https://api-conformance.ebsi.eu/conformance/v3/auth-mock" GENERIC
  issuer: ""
  authorization_endpoint: /auth/authorize
  token_endpoint: /auth/token
  # custom
  direct_post_endpoint: /auth/direct_post
  # end custom
  jwks_uri: /auth/jwks
  scopes_supported:
    - openid
  response_types_supported:
    - vp_token
    - id_token
  response_modes_supported:
    - query
  grant_types_supported:
    - authorization_code
  subject_types_supported:
    - public
  id_token_signing_alg_values_supported:
    - ES256
  request_object_signing_alg_values_supported:
    - ES256
  request_parameter_supported: true
  request_uri_parameter_supported: true
  token_endpoint_auth_methods_supported:
    - private_key_jwt
  vp_formats_supported:
    jwt_vp:
      alg_values_supported:
        - ES256
    jwt_vc:
      alg_values_supported:
        - ES256
  subject_syntax_types_supported:
    - did:key
    - did:ebsi
  subject_trust_frameworks_supported:
    - ebsi
  id_token_types_supported:
    - subject_signed_id_token
    - attester_signed_id_token

credential:
  vc_data_endpoint: /credentials/external-data
  deferred_vc_register: /deferred/register/
  deferred_vc_exchange: /deferred/exchange

authentication:
  session:
    secret: SeCr€t $-load
    expiration: 3600

logs:
  console:
    active: true
    level: debug
  file:
    active: true
    level: debug
    path: "/files/logs/logs.log"
  graylog:
    active: false

language:
  allowed:
    - es
    - en
  default: en
  location: "/shared/files/locales"

developer:
  allow_empty_vc: true
  pre-authorize_data_client: did:key:z2dmzD81cgPx8Vki7JbuuMmFYrWPgYoytykUZ3eyqht1j9Kboj7g9PfXJxbbs4KYegyr7ELnFVnpDMzbJJDDNZjavX6jvtDmALMbXAGW67pdTgFea2FrGGSFs8Ejxi96oFLGHcL4P6bjLDPBJEvRRHSrG4LsPne52fczt2MWjHLLJBvhAC
  pre-authorize_data_vc_type: CTWalletSamePreAuthorisedDeferred
