version: "3"
services:

  backend:
    image: vc-service
    build:
      context: ../
      dockerfile: Dockerfile

    container_name: vc-service
    restart: unless-stopped
    volumes:
      - ./config:/usr/src/app/deploy/config
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NODE_CONFIG_DIR=/usr/src/app/deploy/config
    command: >
      sh -c "npm run start:prod"
    networks:
      - vc-network

networks:
  vc-network:
